# Generated by Django 5.0.6 on 2024-06-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionanalysis',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='emotionanalysis',
            name='score',
        ),
        migrations.AddField(
            model_name='emotionanalysis',
            name='anger',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emotionanalysis',
            name='disgust',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emotionanalysis',
            name='fear',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emotionanalysis',
            name='joy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emotionanalysis',
            name='neutral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emotionanalysis',
            name='sadness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emotionanalysis',
            name='surprise',
            field=models.FloatField(default=0.0),
        ),
    ]
