# Generated by Django 5.0.6 on 2024-09-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_emotionanalysis_emotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionanalysis',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emotionanalysis',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emotionanalysis',
            name='anger',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emotionanalysis',
            name='disgust',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emotionanalysis',
            name='fear',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emotionanalysis',
            name='joy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emotionanalysis',
            name='neutral',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emotionanalysis',
            name='sadness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emotionanalysis',
            name='surprise',
            field=models.FloatField(),
        ),
    ]
